### ISSUE TITLE
How much overhead does running webpack-validator add?

### ISSUE THREAD

**Issue by bebraw** [js-dxtools/webpack-validator#78]
Just curious to know. Maybe it would be a fun stat to show even.

**Comment by jonathanewerner** [comment]
Didn't measure, would guess < 1 sec. You could `time` or `console.time` it :).

**Comment by bebraw** [comment]
Yup, that's what I was thinking. Better try at some point. Perhaps webpack-validator could provide a diagnostic option so we can see better where it's spending its time.

**Comment by jonathanewerner** [comment]
like "webpack config valid (took 320ms)" -- why not, this could alleviate the concern that wrapping the config with a function slows the build down too much. Maybe opt-in via config option "stats" then. Although I'm slightly hesitant to increase the API surface for this use case, I mean not even eslint does have an option like this. Maybe it's overkill and users should do these measurements themselves if needed?

**Comment by bebraw** [comment]
> Maybe it's overkill and users should do these measurements themselves if needed?

That's possible, yeah. You could easily do `module.exports = timeit(validate(config, yourSchema))`. or something like that outside of the validator. Though this would be more difficult from the cli. That would benefit from a flag.

It depends on where you want to draw the line and whether it's a major concern.

**Comment by jonathanewerner** [comment]
Maybe don't make it configurable and color the timing info gray so that it doesn't distract too much from the actual result.

**Comment by bebraw** [comment]
That could work, yeah.

**Comment by nyrosmith** [comment]
Where is the real need for this right now? Wouldn't it be better to focus on actual needs and implement more validation rather than guessing what might be useful for others?
Guessing others needs can be a quite dangerous approach in general. Wouldn't it be useful to define the project scope at this point? There is so much users can do on their own just wrapping everything with a few lines of code...

**Comment by jonathanewerner** [comment]
Well each feature we implement just *presumes* that someone needs it, there is no user research anyway. :) 
I *presume* that people could be hesitant to use this for performance reasons (slow down build time), a little indicator that it's fast could be helpful there. I'm not super convinced though. :)

**Comment by nyrosmith** [comment]
> Well each feature we implement just presumes that someone needs it

I use webpack-validator and all actual features are used by me. That's why I focus at the CLI right now bc I need it and use it every day. 
I think it's a common approach that users who have needs open an issue or send a PR.
I am concerned that this goes in the wrong direction. I quit my last job bc instead of focusing on creating a great and focused product we ended in creating a barbecue grill with an integrated shower which could be configurated acting as a rocket. The PM _knew_ the users needs....

**Comment by jonathanewerner** [comment]
K i just measured, 17ms. Well, i guess we can close this one, perf isn't a concern with joi. :)

**Comment by bebraw** [comment]
Yeah. 17ms is nothing. Thanks.
